/* prettier-ignore */
export const enum ParseError {
    config__fixed_index_collision = 0x01_F,

    message__not_array = 0x01_F,
    message__no_header = 0x02_F,
    message__header_not_array = 0x03_F,
    message__length_less_than_2 = 0x07_F,
    message__header_empty = 0x0A_F,
    message__header_version_not_string = 0x0B_F,
    header__no_key_list = 0x10_F,
    header__key_list_not_array = 0x11_F,
    header__key_not_string = 0x12_F,
    header__key_unknown_format = 0x13_F,
    header__key_duplicate = 0x14_F,
    header__no_encoding_map = 0x20_F,
    header__encoding_map_not_object = 0x21_F,
    header__encoding_map_key_not_reference = 0x24_F,
    header__encoding_map_value_not_string = 0x25_F,
    header__encoding_map_value_not_index = 0x20_F,
    header__encoding_map_key_out_of_bounds = 0x2A_F,
    header__encoding_map_index_out_of_bounds = 0x2B_F,
    header__encoding_map_index_reserved = 0x2C_F, 
    header__no_metadata = 0x30_F,
    header__metadata_not_object = 0x31D_F,
    header__metadata_key_not_reference = 0x36_F,
    header__metadata_key_out_of_bounds = 0x3a_F,

    header__no_root_reference = 0x40_F,
    header__root_reference_not_integer = 0x41_F,
    header__root_reference_out_of_bounds = 0x40_F,
    header__extra_elements = 0x50_F,
    input__unknown_string = 0x10_F,
    input__invalid_type = 0x11_F,
}
